LLM_WORDS_EN = {
    "however", "therefore", "thus", "moreover", "furthermore", "additionally",
    "consequently", "hence", "overall", "notably", "significantly", "indeed",
    "particularly", "specifically", "typically", "generally", "commonly",
    "frequently", "importantly", "essentially", "fundamentally", "crucially",
    "ultimately", "accordingly", "meanwhile", "subsequently", "nevertheless",
    "nonetheless", "similarly", "likewise", "additionally", 
    "arguably", "notably", "remarkably", "clearly", "evidently", "apparently",
    "presumably", "undoubtedly", "likely", "probably", "potentially",
    "essential", "necessary", "relevant", "important", "key", "central",
    "crucial", "significant", "primary", "major", "critical", "noteworthy",
    "overall", "eventually", "ultimately", "consequently", "henceforth",
    "simultaneously", "meanwhile", "previously", "subsequently", "formerly", 
    "currently", "nowadays", "underscores", "leverages", "alternatively", "conversely", 
    "instead", "otherwise", "besides", "afterward", "thereafter",
    "possibly", "presumably", "conceivably", "theoretically", "technically",
    "hypothetically", "tentatively", "intuitively",
    "vital", "valuable", "promising", "impressive", "remarkable", "substantial",
    "notable", "evident", "outstanding", "exceptional", "pivotal", "indispensable",
    "firstly", "secondly", "finally", "collectively", "jointly",
    "respectively", "individually", "separately", "together",
    "strongly", "highly", "substantially", "markedly", "dramatically",
    "considerably", "severely", "moderately", "slightly",
    "thereby", "insofar", "whereby", "herein", "hereafter",
    "framework", "paradigm", "perspective", "context", "approach",
    "phenomenon", "notion", "concept", "insight", "methodology"
}