LLM_WORDS_EN = {
    "however", "therefore", "thus", "moreover", "furthermore", "additionally",
    "consequently", "hence", "overall", "notably", "significantly", "indeed",
    "particularly", "specifically", "typically", "generally", "commonly",
    "frequently", "importantly", "essentially", "fundamentally", "crucially",
    "ultimately", "accordingly", "meanwhile", "subsequently", "nevertheless",
    "nonetheless", "similarly", "likewise", "arguably", "remarkably",
    "clearly", "evidently", "apparently", "presumably", "undoubtedly",
    "likely", "probably", "potentially", "essential", "necessary",
    "relevant", "important", "key", "central", "crucial", "significant",
    "primary", "major", "critical", "noteworthy", "eventually",
    "henceforth", "simultaneously", "previously", "formerly",
    "currently", "nowadays", "underscores", "leverages", "alternatively",
    "conversely", "instead", "otherwise", "besides", "afterward",
    "thereafter", "possibly", "conceivably", "theoretically", "technically",
    "hypothetically", "tentatively", "intuitively", "vital", "valuable",
    "promising", "impressive", "remarkable", "substantial", "notable",
    "evident", "outstanding", "exceptional", "pivotal", "indispensable",
    "firstly", "secondly", "finally", "collectively", "jointly",
    "respectively", "individually", "separately", "together", "strongly",
    "highly", "substantially", "markedly", "dramatically", "considerably",
    "severely", "moderately", "slightly", "thereby", "insofar", "whereby",
    "herein", "hereafter", "framework", "paradigm", "perspective",
    "context", "approach", "phenomenon", "notion", "concept", "insight",
    "methodology", "tapestry", "certainly", "despite", "alternatively",
    "because", "although", "arguably", "ultimately", "navigating", "dive",
    "tailored", "embark", "unlock", "unveil", "elevate", "unleash",
    "harness", "delve", "mastering", "excels", "imagine", "enhance",
    "emphasize", "revolutionize", "foster", "subsequently", "whispering",
    "reverberate", "promptly", "meticulous", "complexities", "realm",
    "understanding", "everchanging", "daunting", "cuttingedge", "robust",
    "power", "bustling", "vibrant", "metropolis", "keen", "fancy",
    "labyrinth", "gossamer", "enigma", "indelible", "landscape",
    "testament", "considerations", "ensure", "essential", "sights",
    "sounds", "remnant", "nestled", "gamechanger"
}
